# Generated by Django 4.0.3 on 2022-03-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='job.company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('info', models.JSONField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('keywords', models.JSONField(null=True)),
                ('skills', models.JSONField(null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('hash', models.BinaryField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('requirements', models.JSONField(null=True)),
                ('requirement_years', models.IntegerField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job.company')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job.companyname')),
            ],
            options={
                'ordering': ['requirement_years', '-created_on', 'description__length'],
            },
        ),
    ]
